release:
  environment: kserve
  application: 
    metadata:
      labels:
        app.kubernetes.io/name: vit-classifier
    modelFormat: pytorch
    versions:
      - inferenceServiceSpecification:
          # weight: 70
          # metadata:
          #   labels:
          #     app.kubernetes.io/version: v0
          spec:
            predictor:
              minReplicas: 2
              serviceAccountName: s3-read-only
              model:
                modelFormat:
                  name: pytorch
                storageUri: s3://tsai-emlo/kserve-ig-2/indian-food-classifier/
                resources:
                  limits:
                    cpu: 2600m
                    memory: 3Gi
        weight: 70
        metadata:
          labels:
            app.kubernetes.io/version: v0
      - inferenceServiceSpecification:
          # weight: 30
          # metadata:
          #   labels:
          #     app.kubernetes.io/version: v1
          spec:
            predictor:
              minReplicas: 2
              serviceAccountName: s3-read-only
              model:
                modelFormat:
                  name: pytorch
                storageUri: s3://tsai-emlo/kserve-ig-2/imagenet-vit/
                resources:
                  limits:
                    cpu: 2600m
                    memory: 3Gi
        weight: 30
        metadata:
          labels:
            app.kubernetes.io/version: v0
    strategy: blue-green