apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wisdom
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/christianh814/kbe-apps.git
    targetRevision: HEAD
    path: 02-working-with-helm/repo
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true