apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vit-classifier
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/satyajitghana/canary-argocd-iter8-kserve.git
    targetRevision: HEAD
    path: vit-classifier
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true